export { default as Main } from './HomePage/Main';
export { default as Login } from './Login';
export { default as ChangePassword } from './ChangePassword';
export { default as Dashboard } from './Dashboard';
export { default as ResetPassword } from './ResetPassword';
export { default as NotFound } from './404Page/404Page';
export { default as Menu } from './MainPage/Menu';
export { default as Service } from './MainPage/Service';
export { default as Me } from './User/Me';
